config/routes.rb
Rails.application.routes.draw do
  root 'properties#index'
  resources :types do
    resources :properties
  end
  resources :publishers do
    resources :properties
  end
  resources :properties do
    resources :galleries
  end

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  belongs_to :property
end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :type
  belongs_to :publisher
  has_many :galleries

  validates :title, presence: true
  def self.view_all
  	$is_view_all=true
  	all.order('created_at DESC')
  end
  def self.view_limit(number)
  	$is_view_all=false
  	all.order('created_at DESC').take(number)
  end
  def view_all?
  	return $is_view_all
  end
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
end

app/models/type.rb
class Type < ActiveRecord::Base
	validates :property_type, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
	def index
		if params[:view_all]
			@properties = Property.view_all
		else
			@properties = Property.view_limit(4)
		end
	end
	def show
		@property = Property.find(params[:id])
		@galleries = @property.galleries
	end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  def index
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
	def display_for(property)
		if ! property.view_all?
			link_to "View All", "#{root_path}/?view_all=true", class: "viewall"
		else
			link_to "Next Page", "#{root_path}/?view_all=true", class: "veiwall"
		end
	end	
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">This footer will always be positioned at the bottom of the page, but <strong>not fixed</strong>.</div>

app/views/layouts/_header.html.erb
<nav>
	<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span> 
      </button>
      <a class="navbar-brand" href= <%= properties_path %> >Locality Real Estate</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", properties_path %></li>
        <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Property
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Rent</a></li>
          <li><%= link_to "About Us" %></li>
        </ul>
      </li>
        <li><a href="#">About Us</a></li> 
      </ul>

      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to " Sign up" , "#", :class => "glyphicon glyphicon-user" %></li>
        <li><%= link_to " Sign in","#", :class => "glyphicon glyphicon-log-in" %></li>
      </ul>
      <div class="col-sm-3 col-md-3 pull-right">
        <form class="navbar-form" role="search">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search" name="srch-term" id="srch-term">
            <div class="input-group-btn">
                <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
        </div>
        </form>
      </div>
      </div>
    </div>
  </nav>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lll</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render "layouts/header" %>

	<%= yield %>
	
</body>
</html>

app/views/properties/index.html.erb
<div id="wrapper">
	<div id="slider-wrapper">
		<div class="slider">
			<div id="sliderFrame">
        <div id="slider">
            <%= image_tag("image-slider-2.jpg", alt: "Building A") %>
            <%= image_tag("image-slider-3.jpg", alt: "Building B") %>
            <%= image_tag("image-slider-4.jpg", alt: "Building C") %>
            <%= image_tag("image-slider-5.jpg", alt: "Building D") %>
        </div>
    	</div>		
		</div>
		<div class="search">
			<form>
				<h3>Property Search</h3>
				<hr/>
				<label>Status</label>
			  <select class="form-control" id="sel1">
				  <option>1</option>
				</select>
			  <label>Beds</label><br/>
			  <input type="text" /><br/>
			  <label>Baths</label><br/>
			  <input type="text"/>
				<fieldset>
	  			<legend>Location:</legend>
	  				<label class="field">City/Province</label>
			  		<select class="field form-control" id="">
				  		<option>1</option>
						</select>
						<label class="field">Sangkat/District</label>
			  		<select class="field form-control" id="">
				  		<option>1</option>
						</select>
	 			</fieldset>
				<br/>
			  <input type="submit" value="Search" class="advance-search-btn">
			  <%= link_to "Advance search","#",:class => 'advancesearch'%>
		  </form>
		</div>
	</div>
	<h2>Newest properties</h2>
	<div id="content-wrapper">
		<section>
			<ul class="grid">
				<% @properties.each do |property| %>
				<li>
					<div class="panel">
						<h4><%= link_to property.title, property_path(property) %></h4>
						<%= image_tag(property.image, class: "image_home" )%>
						<ul class="spec">
							<li>Spec:<%= property.spec %></li>
							<li>Beds:<%= property.beds %></li>
							<li>Baths:<%= property.baths %></li>	
						</ul>
						<p>
							<%= truncate(property.description, length: 250, separator: ' ') %>
						</p>
					</div>
				</li>
				<% end %>
		</ul>
		<%= display_for(@properties[0]) %>
	</section>
	<aside>
		<div id="feature">

		</div>
		<div id="contact">

		</div>
	</aside>
</div>
</div>

app/views/properties/show.html.erb
<div id="wrapper">
	<section>
		<div class="title">
			<h1><%= @property.title %></h1>
		</div>
    <div id='ninja-slider'>
        <div>
            <div class="slider-inner">
                <ul>
                  <%= @galleries.each do | gallery| %>
                    <li><%= image_tag(gallery.image, class:"ns-img") %></li>
                  <% end %>
                </ul>
                <div class="fs-icon" title="Expand/Close"></div>
            </div>
            <div id="thumbnail-slider">
                <div class="inner">
                    <ul>
                        <%= @galleries.each do |gallery| %>
                        <li>
                        	<%= image_tag(gallery.image, class:"thumb") %>
                            <span><%= gallery.description %></span>
                        </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div id="property_info">
      <h2>Description</h2>
    	<hr/>
    	<p>
        <%= @property.description %>
    	</p>
    	<h2>Spec</h2>
    	<hr/>
    	<p>
        <%= @property.spec %> sqm
    	</p>
    	<h2>Beds</h2>
    	<hr/>
    	<p>
    		<%= @property.beds %> beds
    	</p>
      <h2>Bathrrooms</h2>
      <hr/>
      <p>
        <%= @property.baths %> rooms
      </p>
    	<h2>Price</h2>
    	<hr/>
    	<p>
    		<%= number_to_currency(@property.price) %>
    	</p>
      <h2>City/Province</h2>
      <hr/>
      <p>
        <%= @property.state %>
      </p>
      <h2>Sang Kat/District</h2>
      <hr/>
      <p>
        <%= @property.district %>
      </p>
    	<h2>Address</h2>
      <hr/>
      <p>
        <%= @property.address %>
      </p>
      <h2>Map</h2>
      <hr/>
    	<div class="maps">
          <div id="map"></div>
    	</div>
        <h2>Contact person </h2>
        <hr/>
    	<div class="contact">
    		<ul>
          <li><b>Name:&nbsp;</b><%= @property.publisher.name %></li>
          <li><b>Phone:&nbsp;</b><%= @property.publisher.phone %></li>
          <li><b>Email:&nbsp;</b><%= @property.publisher.email %></li>
          <li><b>Role:&nbsp;</b><%= @property.publisher.role %></li>
        </ul>
    	</div>
    </div>
	</section>
	<aside>
		
	</aside>
</div>
<script type="text/javascript">
  var map;
  function initMap() {
    map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: -34.397, lng: 150.644},
      zoom: 8
    });
  }
</script>
<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCkGrrlqIJYcZmwGRxC44-_4_inLrn59ro&callback=initMap">
</script>

app/views/publishers/index.html.erb
<h1>Publishers#index</h1>
<p>Find me in app/views/publishers/index.html.erb</p>

app/views/publishers/new.html.erb
<h1>Publishers#new</h1>
<p>Find me in app/views/publishers/new.html.erb</p>